### ISSUE TITLE
"Bad display name 'Miniaturized kitchen'" in logs

### ISSUE THREAD

**Issue by dikkeduif** [cstahlhut/DailyNeedsMk5#11]
`2020-03-20 10:15:24.519 - Thread:   1 ->  ASSERT: Bad display name 'Miniaturized Kitchen (Daily Needs)' on definition 'MyObjectBuilder_BlueprintDefinition/BuildPlanItem_Assembler/MiniKitchen_DNSK'. It should either be empty, or it must start with 'DisplayName_' and have corresponding text enum defined.

   at Sandbox.Definitions.MyCompositeBlueprintDefinition.Init(MyObjectBuilder_DefinitionBase builder)
   at Sandbox.Game.Entities.Character.MyCharacter.MakeBlueprintFromBuildPlanItem(BuildPlanItem buildPlanItem)
   at Sandbox.Game.Entities.Character.MyCharacter.UpdateBuildPlanner(Boolean synchronize)
   at Sandbox.Game.Gui.MyTerminalInventoryController.WithdrawToInventories(MyInventory[] toInventories, Action`5 getInventoriesMethod, MyEntity interactedEntity, HashSet`1& usedTargetInventories, Nullable`1 persistentMultiple)
   at Sandbox.Game.Gui.MyTerminalInventoryController.Withdraw(MyEntity interactedEntity, MyInventory toInventory, HashSet`1& usedTargetInventories, Nullable`1 persistentMultiple)
   at Sandbox.Game.Gui.MyGuiScreenGamePlay.ProcessWithdraw(MyEntity owner, MyInventory inventory, Nullable`1 multiplier)
   at Sandbox.Game.Gui.MyGuiScreenGamePlay.BuildPlannerControls(MyStringId context)
   at Sandbox.Game.Gui.MyGuiScreenGamePlay.HandleUnhandledInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Game.Gui.MyGuiScreenGamePlay.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyScreenManager.HandleInput()
   at Sandbox.Graphics.GUI.MyDX9Gui.HandleInput()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
`

**Comment by cstahlhut** [comment]
Can't find in logs anywhere anymore. Closing for now.
