### ISSUE TITLE
Putting the mini kitchen crashes the game

### ISSUE THREAD

**Issue by dikkeduif** [cstahlhut/DailyNeedsMk5#12]
I'm using the latest version 1.194 with the frostbite update. It's only crashing when it's almost completed. Looks like it's crashing when MoveLeftArm(), MoveRightArm() or RotateCutter() are called in the Kitchen class. I see the red text appear with "Update error"

`2020-03-20 10:23:33.968 - Thread:   1 ->  ASSERT: MyObjectsPool is full and cannot allocate any other item!

   at Sandbox.Game.Gui.MyHudNotifications.NotificationDrawData.PrepareElements()
   at Sandbox.Game.Gui.MyHudNotifications.Add(MyHudNotificationBase notification)
   at Sandbox.Game.MyVisualScriptLogicProvider.ShowNotificationToAll(String message, Int32 disappearTimeMs, String font)
   at Stollie.DailyNeeds.Kitchen.RotateCutter()
   at Stollie.DailyNeeds.Kitchen.UpdateAfterSimulation()
   at VRage.Game.Components.MyGameLogicComponent.VRage.Game.Entity.EntityComponents.Interfaces.IMyGameLogicComponent.UpdateAfterSimulation(Boolean entityUpdate)
   at VRage.Game.Entity.MyGameLogic.<>c.<UpdateAfterSimulation>b__9_0(MyGameLogicComponent c)
   at VRage.Collections.MyDistributedUpdater`2.Iterate(Action`1 p)
   at VRage.Game.Entity.MyGameLogic.UpdateAfterSimulation()
   at Sandbox.Game.World.MySector.UpdateAfterSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2020-03-20 10:23:33.969 - Thread:   1 ->  ASSERT: MyObjectsPool is full and cannot allocate any other item!

   at Sandbox.Game.Gui.MyHudNotifications.NotificationDrawData.PrepareElements()
   at Sandbox.Game.Gui.MyHudNotifications.Add(MyHudNotificationBase notification)
   at Sandbox.Game.MyVisualScriptLogicProvider.ShowNotificationToAll(String message, Int32 disappearTimeMs, String font)
   at Stollie.DailyNeeds.Kitchen.UpdateAfterSimulation()
   at VRage.Game.Components.MyGameLogicComponent.VRage.Game.Entity.EntityComponents.Interfaces.IMyGameLogicComponent.UpdateAfterSimulation(Boolean entityUpdate)
   at VRage.Game.Entity.MyGameLogic.<>c.<UpdateAfterSimulation>b__9_0(MyGameLogicComponent c)
   at VRage.Collections.MyDistributedUpdater`2.Iterate(Action`1 p)
   at VRage.Game.Entity.MyGameLogic.UpdateAfterSimulation()
   at Sandbox.Game.World.MySector.UpdateAfterSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2020-03-20 10:23:33.972 - Thread:   1 ->  Exception occured: System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.Gui.MyHudNotifications.NotificationDrawData.PrepareElements()
   at Sandbox.Game.Gui.MyHudNotifications.Add(MyHudNotificationBase notification)
   at Sandbox.Game.MyVisualScriptLogicProvider.ShowNotificationToAll(String message, Int32 disappearTimeMs, String font)
   at Stollie.DailyNeeds.Kitchen.UpdateAfterSimulation()
   at VRage.Game.Components.MyGameLogicComponent.VRage.Game.Entity.EntityComponents.Interfaces.IMyGameLogicComponent.UpdateAfterSimulation(Boolean entityUpdate)
   at VRage.Game.Entity.MyGameLogic.<>c.<UpdateAfterSimulation>b__9_0(MyGameLogicComponent c)
   at VRage.Collections.MyDistributedUpdater`2.Iterate(Action`1 p)
   at VRage.Game.Entity.MyGameLogic.UpdateAfterSimulation()
   at Sandbox.Game.World.MySector.UpdateAfterSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
`

**Comment by dikkeduif** [comment]
I've removed some logging in those 3 functions, because I think it caused the crash.

**Comment by cstahlhut** [comment]
Resolved with https://github.com/cstahlhut/DailyNeedsMk5/commit/66a1b0aaeb2f22563bc669e5f386f27a87fe43f5
