### ISSUE TITLE
Critical error on mod load. Failed to load.

### ISSUE THREAD

**Issue by solarsootysmudge** [cstahlhut/DailyNeedsMk5#2]
Following actions taken before error 

1. Install is unzipped master at %appdata%\Roaming\SpaceEngineers\Mods
2. Loaded lost colony map. 
3. Added local mod to mod list.
4. Added API text mod. Loaded after daily needs. 
5. On game start:

MOD_CRITICAL_ERROR: DailyNeedsMk5-master, in file: 
MOD PARTIALLY SKIPPED, LOADED ONLY 1/6 PHASES, Following Error occured:
Object reference not set to an instance of an object.
Sandbox.Game
   at Sandbox.Definitions.MyDefinitionManager.LoadDefinitions(List`1 contexts, List`1 definitionSets, Boolean failOnDebug, Boolean isPreload)
MOD_CRITICAL_ERROR: DailyNeedsMk5-master, in file: 
MOD PARTIALLY SKIPPED, LOADED ONLY 2/6 PHASES, Following Error occured:
Object reference not set to an instance of an object.
Sandbox.Game
   at Sandbox.Definitions.MyDefinitionManager.LoadDefinitions(List`1 contexts, List`1 definitionSets, Boolean failOnDebug, Boolean isPreload)
MOD_CRITICAL_ERROR: DailyNeedsMk5-master, in file: 
MOD PARTIALLY SKIPPED, LOADED ONLY 3/6 PHASES, Following Error occured:
Object reference not set to an instance of an object.
Sandbox.Game
   at Sandbox.Definitions.MyDefinitionManager.LoadDefinitions(List`1 contexts, List`1 definitionSets, Boolean failOnDebug, Boolean isPreload)
MOD_CRITICAL_ERROR: DailyNeedsMk5-master, in file: 
MOD PARTIALLY SKIPPED, LOADED ONLY 4/6 PHASES, Following Error occured:
Object reference not set to an instance of an object.
Sandbox.Game
   at Sandbox.Definitions.MyDefinitionManager.LoadDefinitions(List`1 contexts, List`1 definitionSets, Boolean failOnDebug, Boolean isPreload)
MOD_CRITICAL_ERROR: DailyNeedsMk5-master, in file: 
MOD PARTIALLY SKIPPED, LOADED ONLY 5/6 PHASES, Following Error occured:
Object reference not set to an instance of an object.
Sandbox.Game
   at Sandbox.Definitions.MyDefinitionManager.LoadDefinitions(List`1 contexts, List`1 definitionSets, Boolean failOnDebug, Boolean isPreload)
MOD_CRITICAL_ERROR: DailyNeedsMk5-master, in file: 
MOD PARTIALLY SKIPPED, LOADED ONLY 6/6 PHASES, Following Error occured:
Object reference not set to an instance of an object.
Sandbox.Game
   at Sandbox.Definitions.MyDefinitionManager.LoadDefinitions(List`1 contexts, List`1 definitionSets, Boolean failOnDebug, Boolean isPreload)

No other mods being used apart from API text.

**Comment by solarsootysmudge** [comment]
Could it be that install instructions
> 
3.) Open windows file explorer, in the path bar at the top put this in: - %AppData%\SpaceEngineers\Mods\
>
That points to the old mod folder that is no longer used by Keen. Steam runs the show now and wants mods in the Steam Workshop folder \Steam\steamapps\workshop\content\244850. 

Should the unzipped master be put there instead?

**Comment by solarsootysmudge** [comment]
Resolved. 

Double checked file system since I was pretty sure this was a bad install. Turns out unzip created a double layered master. Getting rid of that fixed the install.

Now all I have to do is figure out why the HUD is not showing yet with the API confirmed working. However that is a problem for another day.
