### ISSUE TITLE
NullReference exception on exit current game (intermittent)

### ISSUE THREAD

**Issue by dikkeduif** [cstahlhut/DailyNeedsMk5#5]
I didn't save the log sorry, but I saw the log.

There was an NullReferenceException in Server.cs function unloadData(). Maybe needs some sanity checks there.

**Comment by dikkeduif** [comment]
`2020-03-18 20:53:36.858 - Thread:   1 ->  Exception occured: VRage.Game.ModAPI.ModCrashedException: Mod crashed! ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Rek.FoodSystem.Server.UnloadData()
   at Sandbox.Game.World.MySession.UnloadDataComponents(Boolean beforeLoadWorld)
   --- End of inner exception stack trace ---
   at Sandbox.Game.World.MySession.UnloadDataComponents(Boolean beforeLoadWorld)
   at Sandbox.Game.World.MySession.Unload()
   at Sandbox.Game.World.MySessionLoader.Unload()
   at Sandbox.Game.World.MySessionLoader.UnloadAndExitToMenu()
   at Sandbox.Graphics.GUI.MyGuiScreenMessageBox.CallResultCallback(ResultEnum val)
   at Sandbox.Graphics.GUI.MyGuiScreenMessageBox.OnClick(ResultEnum result)
   at Sandbox.Graphics.GUI.MyGuiControlButton.HandleInput()
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleControlsInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyScreenManager.HandleInput()
   at Sandbox.Graphics.GUI.MyDX9Gui.HandleInput()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2020-03-18 20:53:36.858 - Thread:   1 ->  InnerException: 
2020-03-18 20:53:36.858 - Thread:   1 ->  Exception occured: System.NullReferenceException: Object reference not set to an instance of an object.
   at Rek.FoodSystem.Server.UnloadData()
   at Sandbox.Game.World.MySession.UnloadDataComponents(Boolean beforeLoadWorld)
2020-03-18 20:53:36.859 - Thread:   1 ->  Showing message
`
